apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    steps:
      - name: Get source
        uses: cloudbees-io/checkout@v1
      - name: Set up Docker Hub registry
        uses: cloudbees-io/configure-oci-credentials@v1
        kind: deploy
        with:
          registry: index.docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build
        kind: build
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: Dockerfile
          destination: docker.io/gmaxey/korean_block_quiz:0.1-${{ cloudbees.version }},docker.io/gmaxey/korean_block_quiz
