apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Get source
        uses: cloudbees-io/checkout@v1
      - name: build
        kind: build
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: Dockerfile
          destination: hub.docker.com/repository/docker/gmaxey/korean_block_quiz:${{ cloudbees.scm.sha }},hub.docker.com/repository/docker/gmaxey/korean_block_quiz
          